app: /Excel/
-
# Note: much of this was generated by Claude. Some commands may need to be double-checked and tweaked.

tag(): user.find_and_replace
tag(): user.tabs

settings():
    # Pasting into a column heading in a PivotTable doesn't work,
    # but typing does
    user.paste_to_insert_threshold = -1

# Test if Talon recognizes Excel
test command: insert("It works!")

# Save workbook as .xlsx format
save as excel: user.excel_save_as_format("Excel Workbook (.xlsx)")

# Copy cell content down to selected cells
fill down: key(ctrl-d)

# Copy cell content right to selected cells
fill right: key(ctrl-r)

# Insert cells, rows, or columns
insert that: key(ctrl-shift-=)

# Delete cells, rows, or columns
delete that: key(ctrl--)

# Open Paste Special dialog
paste special: key(ctrl-alt-v)

# Clear all content, formats, and comments
clear all: user.menu_select("Edit|Clear|All")

# Clear only cell formatting
clear (style | formats): user.menu_select("Edit|Clear|Formats")

# Clear only cell contents
clear that: user.menu_select("Edit|Clear|Contents")

# Clear comments and notes from cells
clear comments: user.menu_select("Edit|Clear|Clear Comments and Notes")

# Remove hyperlinks from cells
clear hyperlinks: user.menu_select("Edit|Clear|Hyperlinks")

# Clear data series
clear series: user.menu_select("Edit|Clear|Series")

# Left align cell content
align left: key(ctrl-l)

# Center align cell content
align center: key(ctrl-e)

# Right align cell content
align right: key(ctrl-r)

# Toggle AutoFilter on/off
filter: key(ctrl-shift-L)

# Open Sort dialog
sort: key(ctrl-shift-r)

# Convert range to table or create new table
table: key(ctrl-t)

# Open Insert Function dialog
formula: key(shift-f3)

# Show AutoComplete dropdown for current cell
complete: key(alt-down)

# Copy formula from cell above (without formatting)
ditto: key(ctrl-shift-')

# Apply bold formatting
bold: key(ctrl-b)

# Apply italic formatting
italic: key(ctrl-i)

# Apply underline formatting
underline: key(ctrl-u)

# Apply strikethrough formatting
strike through: key(ctrl-shift-x)

# Apply General number format
format general: key(ctrl-~)

# Apply Currency format
format currency: key(ctrl-$)

# Apply Percentage format
format (percent | percentage): key(ctrl-%)

# Apply Number format with thousand separators
format (decimal | number): key(ctrl-!)

# Apply Scientific notation format
format exponential: key(ctrl-^)

# Apply Date format
format date: key(ctrl-#)

# Apply Time format
format time: key(ctrl-@)

# Apply outline border to selected cells
cell border: key(ctrl-alt-0)

# Apply left border to selected cells
cell border left: key(ctrl-alt-left)

# Apply right border to selected cells
cell border right: key(ctrl-alt-right)

# Apply top border to selected cells
cell border top: key(ctrl-alt-up)

# Apply bottom border to selected cells
cell border bottom: key(ctrl-alt-down)

# Remove all borders from selected cells
clear cell border: key(ctrl-alt--)

# Select only the active cell (deselect range)
cell select: key(shift-backspace)

# Add or edit cell note
cell note: key(shift-f2)

# Add or edit threaded comment
cell comment: key(ctrl-shift-f2)

# Open Name Manager dialog
cell name: key(ctrl-f3)

# Open context menu for selected cell
cell menu: key(shift-f10)

# Select array formula region containing active cell
array select: key(ctrl-/)

# Hide selected columns
column hide: key(ctrl-0)

# Unhide columns in selection
column unhide: key(ctrl-shift-0)

# Select entire column(s)
column select: key(ctrl-space)

# Insert new column(s)
column insert: key(ctrl-space ctrl-shift-=)

# Delete selected column(s)
column delete: key(ctrl-space ctrl--)

# Move to top of current data region in column
column top: key(ctrl-up)

# Move to bottom of current data region in column
column bottom: key(ctrl-down)

# Auto-fit column width to content
column fit: user.menu_select("Format|Column|AutoFit Selection")

# Navigate to and open column filter dropdown
column filter: key(ctrl-down ctrl-up alt-down)

# Open Column Width dialog
column width: user.menu_select("Format|Column|Width...")

# Hide selected rows
row hide: key(ctrl-9)

# Unhide rows in selection
row unhide: key(ctrl-shift-9)

# Select entire row(s)
row select: key(shift-space)

# Insert new row(s) above selection
row insert [up]: key(shift-space ctrl-shift-=)

# Delete selected row(s)
row delete: key(shift-space ctrl--)

# Move to start of current data region in row
row start: key(ctrl-left)

# Move to end of current data region in row
row end: key(ctrl-right)

# Auto-fit row height to content
row fit: user.menu_select("Format|Row|AutoFit")

# Open Row Height dialog
row height: user.menu_select("Format|Row|Height...")

# Select current table or data region
table select: key(ctrl-a)

# Select entire worksheet
select all: key(ctrl-a ctrl-a ctrl-a)

# Insert new worksheet
sheet new: key(shift-f11)

# Move to previous worksheet tab
sheet previous: key(ctrl-pageup)

# Move to next worksheet tab
sheet next: key(ctrl-pagedown)

# Rename current worksheet
sheet rename:
    key(esc)
    user.menu_select("Format|Sheet|Rename")

# Create PivotTable from selected data
pivot that: user.menu_select("Data|Summarize with PivotTable")

# Share workbook via email
mail this: user.menu_select("File|Share|Send Workbook")

# Navigate to specific cell or range (e.g., "go to B2")
(select | take | go [to]) <user.excel_reference>:
    key(ctrl-g)
    sleep(100ms)
    insert(excel_reference)
    key(return)

# Move to previous cell (left or up in selection)
go previous cell: key(shift-tab)

# Move one cell up
go up: key(up)

# Move one cell down
go down: key(down)

# Move one cell left
go left: key(left)

# Move one cell right
go right: key(right)

# Jump to left edge of data region
jump left: key(ctrl-left)

# Jump to right edge of data region
jump right: key(ctrl-right)

# Jump to top edge of data region
jump up: key(ctrl-up)

# Jump to bottom edge of data region
jump down: key(ctrl-down)

# Jump to next nonblank cell to the left
end left: key(end left)

# Jump to next nonblank cell to the right
end right: key(end right)

# Jump to next nonblank cell above
end up: key(end up)

# Jump to next nonblank cell below
end down: key(end down)

# Move to last used cell in worksheet
go last cell: key(ctrl-end)

# Select from current cell to last used cell
select to last: key(ctrl-shift-end)

# Move to cell A1
go first cell: key(ctrl-home)

# Move to top-left visible cell (requires Scroll Lock on)
go top left: key(home scroll_lock)

# Scroll down one screen
page down: key(pagedown)

# Scroll up one screen
page up: key(pageup)

# Scroll right one screen
page right: key(alt-pagedown)

# Scroll left one screen
page left: key(alt-pageup)

# Move to next cell (right, then down)
next cell: key(tab)

# Move one cell right or to next unlocked cell
(move right | tab): key(tab)

# Show data validation dropdown list
show validation: key(alt-down)

# Enter floating shape navigation mode
cycle shapes: 
    key(ctrl-alt-5)
    key(tab)

# Exit floating shape navigation mode
exit shapes: key(escape)

# Zoom in on worksheet
zoom in: key(ctrl-alt-=)

# Zoom out on worksheet
zoom out: key(ctrl-alt--)

# Alternative: Move one cell up
(cell up | up one): key(up)

# Alternative: Move one cell down
(cell down | down one): key(down)

# Alternative: Move one cell left
(cell left | left one): key(left)

# Alternative: Move one cell right
(cell right | right one): key(right)

# Alternative: Jump to left edge of data
(edge left | jump to left): key(ctrl-left)

# Alternative: Jump to right edge of data
(edge right | jump to right): key(ctrl-right)

# Alternative: Jump to top edge of data
(edge up | jump to top): key(ctrl-up)

# Alternative: Jump to bottom edge of data
(edge down | jump to bottom): key(ctrl-down)

# Alternative: Move to cell A1
top left corner: key(ctrl-home)

# Alternative: Move to last used cell
bottom right corner: key(ctrl-end)
